### ISSUE TITLE
format option on a per directive basis do not override setting in defaults

### ISSUE THREAD

**Issue by binarylandscapes** [Modelmat/sphinxcontrib-drawio#27]
I have in my defaults drawio_output_format = "svg", and put :format: png in my directive. Still creates as a svg. I reverse it and same. it only follows what is in your sphinx defaults or conf.py settings

**Comment by Modelmat** [comment]
This shouldn't be happening. Could I see your directive? (paste using GitHub code formatting).

https://github.com/Modelmat/sphinxcontrib-drawio/blob/f408cfea514f897a69a7e9a2a2d5fa7c1468427b/sphinxcontrib/drawio.py#L117


---
It's probably better to use draw.io's editable PNG / SVG feature, accessible when exporting the file [ I believe saving now as well ]. This makes the file readable to a standard image viewer, yet still allows it to be edited through the draw.io applications.

**Comment by binarylandscapes** [comment]
So this is from my conf.py for basline setup for all docs
```
# Configuration settings for draw.io
#drawio_binary_path = 
drawio_headless = False #svg=False,png=True,pdf=unknown
drawio_output_format = "svg" #svg looks best
```
This is my example directive, where it still outputs in SVG based on the above no matter what the directive says. Now this isn't a problem for me since SVG looks wayyyy better, but I didn't find it cause I found some of their include shapes don't render in svg but do in png even using the windows client.
```
        .. drawio:: example.drawio
            :align: center
            :alt: Example DrawIO File, Sheet 1
            :page-index: 0
            :format: png
            :scale: 1
```

**Comment by ItayZiv** [comment]
Nothing props up right away, don't have too much time rn, but could you clarify on why you disable headless for SVG render?
What environment do you use for building? I don't think you should use headless unless you are actually running without a framebuffer (CI env for example)

And most importantly, if you're looking for SVGs, I 100% recommend switching over to using native draw.io SVGs that can be edited (Instructions from another project: https://docs.wpilib.org/en/latest/docs/contributing/frc-docs/drawio-saving-instructions.html)
They will always look good, they require 0 dependencies, and are SVGs (which retain the original document data and can be edited like a normal drawio file) . If you need you can also save a PNG with the original diagram data, but this might prove less useful, so that's where I can still see this extension being useful. https://desk.draw.io/support/solutions/articles/16000091426-what-filename-to-use- (Note, if you're using it for docs, its better to export because then you can embed any bitmap images in the file so they will always be there)

**Comment by binarylandscapes** [comment]
@ItayZiv yea not sure. All I can say is that using my CentOS8 WSL and my Ubuntu WSL instance if I configure to output in svg I can mark headless=False and if I leave true then I get the following error but it does build

WARNING: Failed to kill Xvfb:n[stderr]
b'kill: sending signal to 4713 failed: No such process\n'
[stdout]
b''
For png output I must use headless=True for document to build.

This may due to the packages I have for my setup which for CentOS8, the WSL instance is built from https://github.com/binarylandscapes/CentWSL/blob/master/Makefile

For Ubuntu (cause I haven't been able to find time to setup a similar autobuild environment yet. I just install from Windows Store and run a script or paste commands installing the matching packages from CentOS8. I do have that in git yet but I attached it.
[ubuntuWSLsetup.txt](https://github.com/Modelmat/sphinxcontrib-drawio/files/4689716/ubuntuWSLsetup.txt)

As far as switching over to using native drawio svgs, my use case is I want to be able to save and work on drawio drawings keeping them in the XML drawio format so it keeps the shapes libraries used include ones I created. Then at anytime I update my sphinx documentation that references it, I don't have to track if I exported the drawing to svg etc. So I use this extension for the automation factor for my documentation as my drawings are large and complicated network and architecture diagrams and this cuts on overhead. Currently with the last release it meets my needs just fine, just during troubleshooting I noticed this didn't appear to be working per the design and thought I would let you know.

I can test and research if keeping in native svg with the complication of my drawings is feasible but the current desktop client leads you to using drawio format.

**Comment by ItayZiv** [comment]
I'll try have a look in the following days, in general without a frame buffer, running without headless should make electron crass right away (and sadly draw.io CLI still relies on the GUI).

As for the native drawio svg, they act as a drop in replacement for the XML file, just with a SVG file added in. You just open the svg in drawio right away and can edit it then save and it will be updated n all.

**Comment by binarylandscapes** [comment]
Ah been playing with the editable SVG and yes I can open and edit just like a drawio file but using it in sphinx displaying it as a figure or image only gives me access to the first sheet. So there is the use case for using the extension to repeat for each sheet. I also tried the editable html file but when embedding in sphinx it tweaks it and some of the lettering is off of the drawing for some reason where a download link to file works files with the javascript windows and being able to switch pages and layers.

**Comment by Modelmat** [comment]
Is this still an issue?

**Comment by binarylandscapes** [comment]
No, this is no longer an issue using 0.0.12. Test was building in latexpdf and had format as svg caused them not to be recognized and included in latexpdf until I removed and let the drawio_builder_export_format value work as intended
