### ISSUE TITLE
Add `--no-sandbox` again, as this seems to be required when running drawio from a docker container

### ISSUE THREAD

**Issue by brechtm** [Modelmat/sphinxcontrib-drawio#29]
This argument to drawio was added in 1da2e44198f37bc933e88629b08c0839e63ceb34 and later removed in 61d0f1909f41893da67dc044715e2796c15bf4b7 because it didn't have any effect. This argument is however required when running drawio inside a docker container and **needs to be at the end of the argument list** (see https://github.com/jgraph/drawio-desktop/issues/249#issuecomment-634157627). Can this argument be added again, possibly controlled by a configuration variable?

**Comment by ItayZiv** [comment]
Just wondering, what happens if you run without that in a docker container?

**Comment by brechtm** [comment]
Without `--no-sandbox` (https://github.com/jgraph/drawio-desktop/issues/144):
```
$ xvfb-run drawio -x --crop packet_structure.drawio -o packet_structure.png
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
Trace/breakpoint trap (core dumped)
```


`--no-sandbox` at the front (https://github.com/jgraph/drawio-desktop/issues/249):
```
 xvfb-run drawio --no-sandbox -x --crop packet_structure.drawio -o packet_structure.png
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
Error: input file/directory not found
```

`--no-sandbox` at the end:
```
$ xvfb-run drawio -x --crop packet_structure.drawio -o packet_structure.png --no-sandbox
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
packet_structure.drawio -> packet_structure.png
```
