### ISSUE TITLE
Improve release versioning & pypi deploys

### ISSUE THREAD

**Issue by Modelmat** [Modelmat/sphinxcontrib-drawio#39]
The current tagged commit system is slightly painful, as if the tags and commits aren't pushed at the same time it sometimes messed up and won't do a deploy.[1]

It would probably be beneficial to have a static version file containing the release version which gets used.

I'm not 100% sure on how we'd get the CI to automatically deploy to pypi [does it need to?] when it changes.

[1] I think, I haven't tested this extensively?
Does GitHub actions support this better?

**Comment by ItayZiv** [comment]
afaik (at least with Github Actions and Azure), if you deploy only on tagged versions it will deploy on tags regardless of commits. So whenever a tag is pushed, it will run whatever steps are set up for deployment, regardless of commits.

**Comment by Modelmat** [comment]
That's how it currently works with CircleCI, but if I remember correctly you have to push both code *and* tags to get it to run the CI. So that's nice for Actions / Azure then.

**Comment by ItayZiv** [comment]
I assume it might also be possible with CircleCI, the trigger for running the CI needs to be both tags and commits, and then if the event triggering it is a tag, then you deploy. (iirc CircleCI lets you check for a tag on a commit that triggered CI, Actions only lets you check if the event that triggered CI is a tag or not)

**Comment by brechtm** [comment]
I tagged 0.0.11 in order to get a new release out, but something went wrong. I did push the tag separately from the commit, but the [deploy step on CircleCI](https://app.circleci.com/pipelines/github/Modelmat/sphinxcontrib-drawio/129/workflows/9952265d-9e74-4d17-bf96-75a38e7404cf/jobs/318) still got launched. Unfortunately, it produced distribution packages with version 0.10!

**Comment by Modelmat** [comment]
This was changed through #43. I decided to go with requiring a specific "version" update commit which can then be tagged. I'm intending to document this with #40, but I haven't got around to it (and won't due to exams).
Also with #41 I'd like to make it release to pypi on a github "release", so that it becomes an explicit action in order to release it to pypi, rather than a tagging and pushing.

**Comment by brechtm** [comment]
Sorry, I was not aware of these changes. To make things worse, version 0.10.0 that is now on PyPI is broken (_cannot import name '__version__'). Can you delete this release from PyPI to prevent users from accidentally updating to this broken version? Note that we will not be able to reuse the 0.10.0 version on PyPI, however. We won't be able to overwrite the 0.10.0 packages anyway...

**Comment by Modelmat** [comment]
Oops, my bad. That's been deleted from PyPi now.
I've also accidentally made it "0.10.0" instead of "0.0.10", so double oops.
