### ISSUE TITLE
It is not valid to have a sphinxcontrib/__init__.py

### ISSUE THREAD

**Issue by brechtm** [Modelmat/sphinxcontrib-drawio#44]
_sphinxcontrib_ is a [namespace package](https://packaging.python.org/guides/packaging-namespace-packages/) shared by multiple distributions. I think you should not add an `__init__.py` in it. I believe this causes the import error on the tag 0.0.11 (released as 0.10.0).

See the section [Native namespace packages](https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages):

> It is extremely important that every distribution that uses the namespace package omits the __init__.py or uses a pkgutil-style __init__.py. If any distribution does not, it will cause the namespace logic to fail and the other sub-packages will not be importable.

**Comment by brechtm** [comment]
Testing with tox or nox would have caught this issue, as the package is first installed before tests are run.

**Comment by Modelmat** [comment]
I think it might be a good idea to get our own directory, since `sphinxcontrib` is really for the sphinx-contrib project, which this isn't affiliated with. I believe it was created like that since I was it as an example, so it could be a good idea to rename `sphinxcontrib` to `sphinxcontrib-drawio` and this avoids this issue entirely.

**Comment by brechtm** [comment]
Changing the package name will require users to update the entry in the extension list in _conf.py_. You could also put everything under `sphinxcontrib/drawio/`, if you want to have an `__init__.py`. This will keep the module (now a package) name the same.

**Comment by brechtm** [comment]
Please don't let this get in the way of your exams. Can we perhaps simply revert a9f9ac8c471678eca7d81de9eb04354a2921866e for now so we can release 0.0.11?

**Comment by Modelmat** [comment]
Yep, that's fine. If you want to merge #45 that's fine.
