### ISSUE TITLE
xvfb-run doesn't exist on windows

### ISSUE THREAD

**Issue by jobec** [Modelmat/sphinxcontrib-drawio#5]
By default, `drawio_headless` is `True`. But that triggers errors on windows.

Autodetecting windows and setting `drawio_headless` to `False` removes one troubleshooting step for users on windows.

**Comment by Modelmat** [comment]
I've decided to rework how this is done; the reason why I had this as `True` by default.. was that the CI required headless enabled. Of course, I can just enable it locally...

So this should work now without needing to install xvfb-run.
