### ISSUE TITLE
Stop clearing PDF scale args

### ISSUE THREAD

**Issue by modelmat** [modelmat/sphinxcontrib-drawio#53]
https://github.com/Modelmat/sphinxcontrib-drawio/blob/7155c36fa792b22553de6edf4da7e39c1ccd03d1/sphinxcontrib/drawio/__init__.py#L182

Mentions the issue 344 which is now fixed on later versions.

**Comment by brechtm** [comment]
If this doesn't break operation for newer drawio versions, I would keep this in the code for now so that old versions continue to work well.

**Comment by Modelmat** [comment]
Okay, maybe we should just note this in code.
